apiVersion: apps/v1
kind: Deployment
metadata:
  name: mustad-ecr-poc
spec:
  selector:
    matchLabels:
      run: mustad-ecr-poc
  replicas: 2
  template:
    metadata:
      labels:
        run: mustad-ecr-poc
    spec:
      containers:
      - name: mustad-ecr-poc
        image: nginx 
        ports:
        - containerPort: 80
