apiVersion: apps/v1
kind: Deployment
metadata:
  name: mustad-ecr-poc
spec:
  selector:
    matchLabels:
      run: mustad-ecr-poc
  replicas: 4
  template:
    metadata:
      labels:
        run: mustad-ecr-poc
    spec:
      containers:
      - name: mustad-ecr-poc
        image: 034165090723.dkr.ecr.ap-northeast-2.amazonaws.com/mustad-ecr-poc:8614
        ports:
        - containerPort: 80
